Repository FundingBoost/FundingBoost-Client, pull requests merged in 2024-06, with the labels that each got.

#46 ✨ Feat: oauth 로그인 구현 - redirect를 위한 중간 페이지 생성 및 라우터 설정
  .github/pull_request_template.md
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/pages/login-page/redirection.jsx
  fundingboost/src/router.jsx
Labels: :sparkles: Feature

#47 ✨[FF-71] v2 refactor
  fundingboost/src/components/atoms/OrderPayPayment/orderpaypayment.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/button/purchaseBtn/purchaseBtn.jsx
  fundingboost/src/components/atoms/mypage-myfunding-fin-btn/mypage-myfunding-fin-btn.scss
  fundingboost/src/components/atoms/mypage-myfunding-singleitem/mypage-myfunding-singleitem.jsx
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-CurrentPay/friendFundingPay-CurrentPay.jsx
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.jsx
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.scss
  fundingboost/src/components/molecules/Mypay-Payment/mypay-payment.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/order-pay/order-pay.jsx
  fundingboost/src/components/organisms/header/header.scss
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#48 ✨[FF-69] pagination 무한 스크롤 적용 및 에러 핸들링 적용
  fundingboost/src/assets/error.svg
  fundingboost/src/components/atoms/OrderPayPayment/orderpaypayment.jsx
  fundingboost/src/components/atoms/Shopping-Item-Category/shopping-item-category.jsx
  fundingboost/src/components/atoms/Shopping-Item-Category/shopping-item-category.scss
  fundingboost/src/components/atoms/buttons/ErrorButton/error-btn.jsx
  fundingboost/src/components/atoms/buttons/ErrorButton/error-btn.scss
  fundingboost/src/components/atoms/shopping-single-item/shopping-single-item.scss
  fundingboost/src/components/molecules/MainRankingList/mainrankingitem.jsx
  fundingboost/src/components/molecules/Mypay-Payment/mypay-payment.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/organisms/contents/error-handle/error-handle.jsx
  fundingboost/src/components/organisms/contents/error-handle/error-handle.scss
  fundingboost/src/components/organisms/contents/main/main.jsx
  fundingboost/src/components/organisms/contents/main/main.scss
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/pages/error-handle-page/error-handle-page.jsx
  fundingboost/src/components/pages/error-handle-page/error-handle-page.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/index.js
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :postbox: API, :sparkles: Feature

#49 ✨ [FF-72] Oauth 리팩토링 및 상태관리 수정
  fundingboost/src/App.jsx
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.jsx
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.scss
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-CurrentPay/friendFundingPay-CurrentPay.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-nonfunding.scss
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.scss
  fundingboost/src/components/molecules/Single-friendFunding/single-friendFunding.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.jsx
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/molecules/orderHistory-singleOrder/orderHistory-singleOrder.jsx
  fundingboost/src/components/molecules/singleReview/singleReview.jsx
  fundingboost/src/components/molecules/wishList-SingleItem/wishList-SingleItem.jsx
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/login-page/login-page.jsx
  fundingboost/src/components/pages/login-page/redirection.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/components/pages/mypage/mypage-delivery-management-page/mypage-delivery-management-page.jsx
  fundingboost/src/components/pages/mypage/mypage-friend-funding-history-page/mypage-friend-funding-history-page.jsx
  fundingboost/src/components/pages/mypage/mypage-funding-history-page/mypage-myfunding-history-page.jsx
  fundingboost/src/components/pages/mypage/mypage-myfunding-page/mypage-myfunding-page.jsx
  fundingboost/src/components/pages/mypage/mypage-order-history-page/mypage-order-history-page.jsx
  fundingboost/src/components/pages/mypage/mypage-review-page/mypage-review-page.jsx
  fundingboost/src/components/pages/mypage/mypage-wishlist-page/mypage-wishlist-page.jsx
  fundingboost/src/components/pages/pay-success-page/pay-success-page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#51 ✨ [FF-67] 쇼핑상세 리팩토링
  fundingboost/src/assets/shoppingDetailTest.PNG
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.scss
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.scss
  fundingboost/src/components/atoms/Shopping-Detail-defaultText/shopping-Detail-defaultText.jsx
  fundingboost/src/components/atoms/Shopping-Detail-defaultText/shopping-Detail-defaultText.scss
  fundingboost/src/components/atoms/button/fundingNowBtn/fundingNowBtn.jsx
  fundingboost/src/components/atoms/button/purchaseBtn/purchaseBtn.jsx
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.scss
  fundingboost/src/components/atoms/gifthubModal/gifthubModal.jsx
  fundingboost/src/components/atoms/gifthubModal/gifthubModal.scss
  fundingboost/src/components/atoms/shoppingDetail-nonMemberModal/shoppingDetail-nonMemberModal.jsx
  fundingboost/src/components/atoms/shoppingDetail-nonMemberModal/shoppingDetail-nonMemberModal.scss
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.scss
  fundingboost/src/components/molecules/mainFunding/mainFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.scss
  fundingboost/src/components/organisms/contents/login/login.scss
  fundingboost/src/components/organisms/contents/main/main.scss
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.scss
Labels: :hammer: Refactor, :sparkles: Feature

#52 ✨ [FF-73] v3 krampoline setting 01
  Dockerfile
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Item-Category/shopping-item-category.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.scss
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/login-page/redirection.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#53 ✨ [FF-74] v3 test refactor
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug

#54 🚀 [Deploy] V3 배포 / Main 브랜치 merge
  Dockerfile
  fundingboost/src/assets/shoppingDetailTest.PNG
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.scss
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.scss
  fundingboost/src/components/atoms/Shopping-Detail-defaultText/shopping-Detail-defaultText.jsx
  fundingboost/src/components/atoms/Shopping-Detail-defaultText/shopping-Detail-defaultText.scss
  fundingboost/src/components/atoms/Shopping-Item-Category/shopping-item-category.jsx
  fundingboost/src/components/atoms/button/fundingNowBtn/fundingNowBtn.jsx
  fundingboost/src/components/atoms/button/purchaseBtn/purchaseBtn.jsx
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.scss
  fundingboost/src/components/atoms/gifthubModal/gifthubModal.jsx
  fundingboost/src/components/atoms/gifthubModal/gifthubModal.scss
  fundingboost/src/components/atoms/shoppingDetail-nonMemberModal/shoppingDetail-nonMemberModal.jsx
  fundingboost/src/components/atoms/shoppingDetail-nonMemberModal/shoppingDetail-nonMemberModal.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.scss
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.scss
  fundingboost/src/components/molecules/mainFunding/mainFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.scss
  fundingboost/src/components/organisms/contents/login/login.scss
  fundingboost/src/components/organisms/contents/main/main.scss
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.scss
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/login-page/redirection.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :earth_asia: Deploy

#55 ✨ [FF-75] fix bug 01
  fundingboost/src/components/atoms/Calendar/calender.jsx
  fundingboost/src/components/atoms/FundingMessage/fundingMessage.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#56 🚀 [Deploy] V3 버그 수정 버전 배포 / Main 브랜치 merge
  fundingboost/src/components/atoms/Calendar/calender.jsx
  fundingboost/src/components/atoms/FundingMessage/fundingMessage.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :earth_asia: Deploy

#58 ✨ [FF-76] fix bug 02
  fundingboost/src/components/atoms/MyPageMyfundingJoinFriend/MyPageMyfundingJoinFriend.scss
  fundingboost/src/components/atoms/mypage-myfunding-singleitem/mypage-myfunding-singleitem.scss
  fundingboost/src/components/molecules/MyPageFriendFundingList/mypage-friend-funding-list.scss
  fundingboost/src/components/molecules/MyPageMyFundingHistoryList/mypage-myfunding-history-list.scss
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.scss
Labels: :lady_beetle: bug
