Repository FundingBoost/FundingBoost-Client, pull requests merged in 2024-04, with the labels that each got.

#1 [docs] : update README.md
  fundingboost/README.md
Labels: :page_with_curl: Docs

#4 FF-2 footer
  fundingboost/package.json
  fundingboost/src/App.css
  fundingboost/src/App.js
  fundingboost/src/assets/empty.png
  fundingboost/src/assets/logo.png
  fundingboost/src/components/organisms/footer/footer.jsx
  fundingboost/src/components/organisms/footer/footer.scss
Labels: :hammer: Refactor, :sparkles: Feature

#5 ✨ [FF-4] login 페이지 개발 및 main, login 라우터 설정
  fundingboost/package.json
  fundingboost/src/App.css
  fundingboost/src/App.js
  fundingboost/src/App.jsx
  fundingboost/src/assets/loginmoji.svg
  fundingboost/src/assets/sociallogin/applelogin.png
  fundingboost/src/assets/sociallogin/googlelogin.png
  fundingboost/src/assets/sociallogin/kakaologin.png
  fundingboost/src/assets/sociallogin/naverlogin.png
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/login/login.scss
  fundingboost/src/components/orgenisms/header/header.jsx
  fundingboost/src/components/orgenisms/header/header.scss
  fundingboost/src/components/pages/login-page/login-page.jsx
  fundingboost/src/components/pages/login-page/login-page.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/components/pages/main-page/main-page.scss
  fundingboost/src/logo.svg
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#6 ✨ [FF-7] Main 페이지 Ranking Pane 개발
  fundingboost/src/assets/ranking/allranking.png
  fundingboost/src/assets/ranking/manranking.png
  fundingboost/src/assets/ranking/womanranking.png
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/ManButton/manbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/ManButton/manbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/WomanButton/womanbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/WomanButton/womanbutton.scss
  fundingboost/src/components/molecules/MainRankingList/mainrankingitem.jsx
  fundingboost/src/components/molecules/MainRankingList/mainrankingitem.scss
  fundingboost/src/components/molecules/RankingItemPane/rankingitempane.jsx
  fundingboost/src/components/molecules/RankingItemPane/rankingitempane.scss
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.jsx
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.scss
  fundingboost/src/components/organisms/contents/main/main.jsx
  fundingboost/src/components/organisms/contents/main/main.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/utils/formats.js
Labels: :hammer: Refactor, :sparkles: Feature

#7 ✨ [FF-5] Main 페이지 MyFunding 개발
  fundingboost/src/App.js
  fundingboost/src/assets/defaultProfile.svg
  fundingboost/src/assets/nonItemImg.svg
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.jsx
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.scss
  fundingboost/src/components/atoms/button/mainMyfuudingBtn/checkFunding-btn.jsx
  fundingboost/src/components/atoms/button/mainMyfuudingBtn/logingo-btn.jsx
  fundingboost/src/components/atoms/button/mainMyfuudingBtn/startFunding-btn.jsx
  fundingboost/src/components/atoms/button/yellowBtn.scss
  fundingboost/src/components/atoms/gauge-bar/gauge-bar.jsx
  fundingboost/src/components/atoms/gauge-bar/gauge-bar.scss
  fundingboost/src/components/atoms/itemImg/itemImg.jsx
  fundingboost/src/components/atoms/itemImg/itemImg.scss
  fundingboost/src/components/atoms/mainMyFunding/mainMyFundingStatus.jsx
  fundingboost/src/components/atoms/mainMyFunding/mainMyFundingStatus.scss
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.jsx
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.scss
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/organisms/header/header.scss
Labels: :hammer: Refactor, :sparkles: Feature

#10 ✨ [FF-16] funding regist 페이지 개발
  fundingboost/src/components/atoms/Calendar/calender.jsx
  fundingboost/src/components/atoms/Calendar/calender.scss
  fundingboost/src/components/atoms/FundingMessage/fundingMessage.jsx
  fundingboost/src/components/atoms/FundingMessage/fundingMessage.scss
  fundingboost/src/components/atoms/button/FundingRegistBtn/fundingRegistBtn.jsx
  fundingboost/src/components/atoms/button/FundingTagBtn/fundingTagBtn.jsx
  fundingboost/src/components/atoms/button/FundingTagBtn/fundingTagBtn.scss
  fundingboost/src/components/atoms/button/yellowBtn.scss
  fundingboost/src/components/atoms/itemImg/itemImg.jsx
  fundingboost/src/components/atoms/itemImg/itemImg.scss
  fundingboost/src/components/molecules/FundingItem/FundingRegistItem/FundingItem.jsx
  fundingboost/src/components/molecules/FundingItem/FundingRegistItem/FundingItem.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.scss
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#9 ✨[FF-28] Gifthub 페이지 프로필 및 페이지 컴포넌트 개발
  fundingboost/src/assets/testprofile.svg
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/AllButton/allbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/ManButton/manbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.jsx
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.scss
  fundingboost/src/components/atoms/buttons/MainRankingButton/WomanButton/womanbutton.jsx
  fundingboost/src/components/molecules/MypageIndex/mypageindex.jsx
  fundingboost/src/components/molecules/MypageIndex/mypageindex.scss
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.jsx
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.scss
  fundingboost/src/components/molecules/RankingItemPane/rankingitempane.jsx
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.jsx
  fundingboost/src/components/organisms/contents/mypage/mypage.jsx
  fundingboost/src/components/organisms/contents/mypage/mypage.scss
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/mypage-page/mypage-page.jsx
  fundingboost/src/components/pages/mypage-page/mypage-page.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#11 ✨ [FF-32] 라우터 수정 및 로딩 스피너 추가
  fundingboost/package.json
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/router.jsx
Labels: :lady_beetle: bug, :sparkles: Feature
