Repository FundingBoost/FundingBoost-Client, pull requests merged in 2024-05, with the labels that each got.

#12 ✨ [FF-34] Gifthub 페이지 props 전달
  fundingboost/src/components/atoms/buttons/MainRankingButton/RankingMostButton/mostfundingbutton.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/molecules/GifthubResult/gifthubresult.jsx
  fundingboost/src/components/molecules/Modal/GifthubOptionCount/gifthuboptioncount.jsx
  fundingboost/src/components/molecules/Modal/GifthubOptionCount/gifthuboptioncount.scss
  fundingboost/src/components/molecules/RankingItemPane/rankingitempane.scss
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.jsx
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.scss
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.jsx
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/gifthub-page/gifthub-page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#13 [FF-31] funding regist 페이지 post 전송
  fundingboost/src/components/atoms/Calendar/calender.jsx
  fundingboost/src/components/atoms/Calendar/calender.scss
  fundingboost/src/components/atoms/FundingMessage/fundingMessage.jsx
  fundingboost/src/components/atoms/button/FundingRegistBtn/fundingRegistBtn.jsx
  fundingboost/src/components/atoms/button/FundingTagBtn/fundingTagBtn.jsx
  fundingboost/src/components/atoms/button/FundingTagBtn/fundingTagBtn.scss
  fundingboost/src/components/atoms/button/yellowBtn.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.scss
  fundingboost/src/components/organisms/footer/footer.scss
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#14 ✨ FF 35 Fix bug
  fundingboost/package.json
  fundingboost/src/components/molecules/RankingItemPane/rankingitempane.scss
  fundingboost/src/components/molecules/RankingPersonPane/rankingpersonpane.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/main/main.jsx
Labels: :lady_beetle: bug

#15 [FF-38] funding regist 페이지 post 전송
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor

#16 [FF-30] main페이지 myfunding 데이터 통신, Carousel 수정
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.jsx
  fundingboost/src/components/atoms/ProfileImg/ProfileImg.scss
  fundingboost/src/components/atoms/gauge-bar/gauge-bar.jsx
  fundingboost/src/components/atoms/itemImg/itemImg.jsx
  fundingboost/src/components/atoms/itemImg/itemImg.scss
  fundingboost/src/components/molecules/mainMyfunding/mainMyfunding/mainMyFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/mainMyfunding/mainMyfunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#17 [FF-10] main페이지 friendFunding 개발
  fundingboost/src/assets/hweng.svg
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.scss
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendNoFunding/mainFriendNoFunding.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendNoFunding/mainFriendNoFunding.scss
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/molecules/mainFunding/mainFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#18 ✨ [FF-37] Mypage Myfunding (nonfunding, funding, finish)
  fundingboost/src/assets/messagebox-open.svg
  fundingboost/src/assets/messagebox.svg
  fundingboost/src/assets/mypageDefaultProfile.svg
  fundingboost/src/assets/nonItemImg.svg
  fundingboost/src/assets/testitem.svg
  fundingboost/src/components/atoms/MyPageMyfundingJoinFriend/MyPageMyfundingJoinFriend.jsx
  fundingboost/src/components/atoms/MyPageMyfundingJoinFriend/MyPageMyfundingJoinFriend.scss
  fundingboost/src/components/atoms/MyPageMyfundingJoinFriendGroup/MyPageMyfundingJoinFriendGroup.jsx
  fundingboost/src/components/atoms/MyPageMyfundingJoinFriendGroup/MyPageMyfundingJoinFriendGroup.scss
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-complete-button/mypage-complete-button.scss
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-delivery-button/mypage-delivery-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-delivery-button/mypage-delivery-button.scss
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.scss
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-remainpay-button/mypage-remainpay-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-remainpay-button/mypage-remainpay-button.scss
  fundingboost/src/components/atoms/gauge-bar/gauge-bar.scss
  fundingboost/src/components/atoms/itemImg/itemImg.jsx
  fundingboost/src/components/atoms/mypage-additional-info/mypage-additional-info.jsx
  fundingboost/src/components/atoms/mypage-additional-info/mypage-additional-info.scss
  fundingboost/src/components/atoms/mypage-myfunding-gauge/mypage-myfunding-gauge.jsx
  fundingboost/src/components/atoms/mypage-myfunding-gauge/mypage-myfunding-gauge.scss
  fundingboost/src/components/atoms/mypage-myfunding-singleitem/mypage-myfunding-singleitem.jsx
  fundingboost/src/components/atoms/mypage-myfunding-singleitem/mypage-myfunding-singleitem.scss
  fundingboost/src/components/molecules/Modal/MypageMyfundingMessage/mypagemyfundingmessage.jsx
  fundingboost/src/components/molecules/Modal/MypageMyfundingMessage/mypagemyfundingmessage.scss
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.scss
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-finfunding.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-finfunding.scss
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-nonfunding.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-nonfunding.scss
  fundingboost/src/components/molecules/MypageIndex/mypageindex.jsx
  fundingboost/src/components/molecules/MypageIndex/mypageindex.scss
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.jsx
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.scss
  fundingboost/src/components/molecules/mypage-myfunding-itemlist/mypage-myfunding-itemlist.jsx
  fundingboost/src/components/molecules/mypage-myfunding-itemlist/mypage-myfunding-itemlist.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.jsx
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.scss
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.scss
  fundingboost/src/components/organisms/contents/mypage/mypage.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/mypage-page/mypage-page.jsx
  fundingboost/src/components/pages/mypage/mypage-funding-history-page/mypage-myfunding-history-page.jsx
  fundingboost/src/components/pages/mypage/mypage-funding-history-page/mypage-myfunding-history-page.scss
  fundingboost/src/components/pages/mypage/mypage-myfunding-page/mypage-myfunding-page.jsx
  fundingboost/src/components/pages/mypage/mypage-myfunding-page/mypage-myfunding-page.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#19 🐛 fix bug
  fundingboost/src/assets/share.svg
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-complete-button/mypage-complete-button.jsx
Labels: :lady_beetle: bug

#20 [FF-39] fundingRegist페이지 상품 순서 지정 추가, 디테일 수정
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.scss
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.scss
Labels: :hammer: Refactor, :sparkles: Feature

#21 ✨[FF-40] main페이지 개발
  fundingboost/src/components/atoms/button/yellowBtn.scss
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberNoFunding/memberNoFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.jsx
  fundingboost/src/components/molecules/mainMyfunding/memberYesFunding/memberYesFunding.scss
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.jsx
  fundingboost/src/components/molecules/mainMyfunding/nonMember/nonMember.scss
Labels: :hammer: Refactor, :sparkles: Feature

#23 ✨ [FF-43] 마이페이지 MY펀딩 refactor, Pay-Success 페이지
  fundingboost/src/assets/pay-success.svg
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-myfunding-extension-button/mypage-myfunding-extension-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-myfunding-extension-button/mypage-myfunding-extension-button.scss
  fundingboost/src/components/atoms/buttons/PaysuccessButton/paysuccessbutton.scss
  fundingboost/src/components/atoms/buttons/PaysuccessButton/paysuccessubutton.jsx
  fundingboost/src/components/atoms/mypage-myfunding-fin-btn/mypage-myfunding-fin-btn.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.scss
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-finfunding.jsx
  fundingboost/src/components/organisms/contents/paysuccess/paysuccess.jsx
  fundingboost/src/components/organisms/contents/paysuccess/paysuccess.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :postbox: API, :sparkles: Feature

#24 ✨ [FF-42] 친구펀딩 상세 페이지 생성 및 데이터 통신
  fundingboost/src/assets/airplane.png
  fundingboost/src/assets/friendFunding/receipt.svg
  fundingboost/src/components/atoms/button/FriendToFundingBtn/FriendToFundingBtn.jsx
  fundingboost/src/components/atoms/button/friendFundingDetail-moneybuttonGroup/friendFundingDetail-moneybuttonGroup.jsx
  fundingboost/src/components/atoms/button/friendFundingDetail-moneybuttonGroup/friendFundingDetail-moneybuttonGroup.scss
  fundingboost/src/components/atoms/button/yellowBtn.scss
  fundingboost/src/components/atoms/friendFundingDetail-friendFunding/friendFundingDetail-friendFunding.jsx
  fundingboost/src/components/atoms/friendFundingDetail-friendFunding/friendFundingDetail-friendFunding.scss
  fundingboost/src/components/atoms/friendFundingDetail-profileMessage/friendFundingDetail-profileMessage.jsx
  fundingboost/src/components/atoms/friendFundingDetail-profileMessage/friendFundingDetail-profileMessage.scss
  fundingboost/src/components/atoms/point/pointUse.jsx
  fundingboost/src/components/atoms/point/pointUse.scss
  fundingboost/src/components/molecules/FriendFundingDetail/FriendFundingDetail-item/friendFundingDetail-item.jsx
  fundingboost/src/components/molecules/FriendFundingDetail/FriendFundingDetail-item/friendFundingDetail-item.scss
  fundingboost/src/components/molecules/FriendFundingDetail/friendFundingDetail-optionDetail/friendFundingDetail-optionDetail.jsx
  fundingboost/src/components/molecules/FriendFundingDetail/friendFundingDetail-optionDetail/friendFundingDetail-optionDetail.scss
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.jsx
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.scss
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.scss
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#28 ✨ [FF-46] friend funding pay 페이지 개발 및 friendfundingDetail 페이지 refactor
  fundingboost/src/assets/friendFunding/barcode-image.svg
  fundingboost/src/assets/friendFunding/receipt.svg
  fundingboost/src/components/atoms/button/FriendToFundingBtn/FriendToFundingBtn.jsx
  fundingboost/src/components/atoms/button/friendfundingPaymentBtn/friendfundingPaymentBtn.jsx
  fundingboost/src/components/atoms/friendFundingDetail-friendFunding/friendFundingDetail-friendFunding.jsx
  fundingboost/src/components/atoms/friendFundingDetail-profileMessage/friendFundingDetail-profileMessage.jsx
  fundingboost/src/components/atoms/point/pointUse.jsx
  fundingboost/src/components/atoms/point/pointUse.scss
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-CurrentPay/FriendFundingPay-CurrentPay.scss
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-CurrentPay/friendFundingPay-CurrentPay.jsx
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-Price/friendFundingPay-Price.jsx
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-Price/friendFundingPay-Price.scss
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-barcode/friendFundingPay-barcode.jsx
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-barcode/friendFundingPay-barcode.scss
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-profile/friendFundingPay-profile.jsx
  fundingboost/src/components/molecules/FriendFundingPay/FriendFundingPay-profile/friendFundingPay-profile.scss
  fundingboost/src/components/molecules/mainFriendFunding/mainFriendFunding/mainFriendFunding.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.scss
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#29 ✨ [FF-50] friend funding 페이지 개발
  fundingboost/src/components/atoms/friendFunding-DropdownBtn/friendFunding-DropdownBtn.jsx
  fundingboost/src/components/atoms/friendFunding-DropdownBtn/friendFunding-DropdownBtn.scss
  fundingboost/src/components/atoms/friendFunding-itemImg/friendFunding-itemImg.jsx
  fundingboost/src/components/atoms/friendFunding-itemImg/friendFunding-itemImg.scss
  fundingboost/src/components/atoms/friendFunding-profile-Dday/friendFunding-profile-Dday.jsx
  fundingboost/src/components/atoms/friendFunding-profile-Dday/friendFunding-profile-Dday.scss
  fundingboost/src/components/molecules/Single-friendFunding/single-friendFunding.jsx
  fundingboost/src/components/molecules/Single-friendFunding/single-friendFunding.scss
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#30 ✨ [FF-49] Shopping Detail 페이지 제작
  fundingboost/src/assets/emptyheart.svg
  fundingboost/src/assets/fillheart.svg
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Info/shopping-detail-info.scss
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.scss
  fundingboost/src/components/atoms/shopping-single-item/shopping-single-item.jsx
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.scss
  fundingboost/src/components/pages/friendFunding-detail-page/friendFundingDetail-page.jsx
  fundingboost/src/components/pages/friendFunding-detail-page/friendFundingDetail-page.scss
  fundingboost/src/components/pages/shopping-detail-page/shopping-detail-page.jsx
  fundingboost/src/components/pages/shopping-detail-page/shopping-detail-page.scss
  fundingboost/src/router.jsx
Labels: :lady_beetle: bug, :sparkles: Feature

#34 ✨ FF-58 sign up page 개발 및 환경변수 , main페이지 refactor, 쇼핑 style 수정
  fundingboost/src/components/atoms/button/friendfundingPaymentBtn/friendfundingPaymentBtn.jsx
  fundingboost/src/components/atoms/button/signUpBtn/signUpBtn.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-myfunding-extension-button/mypage-myfunding-extension-button.jsx
  fundingboost/src/components/atoms/friendFunding-profile-Dday/friendFunding-profile-Dday.scss
  fundingboost/src/components/atoms/shopping-single-item/shopping-single-item.jsx
  fundingboost/src/components/atoms/shopping-single-item/shopping-single-item.scss
  fundingboost/src/components/molecules/MainRankingList/mainrankingitem.jsx
  fundingboost/src/components/molecules/MainRankingList/mainrankingitem.scss
  fundingboost/src/components/molecules/Modal/GifthubOptionCount/gifthuboptioncount.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/molecules/Single-friendFunding/single-friendFunding.scss
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.jsx
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/molecules/signUp/signUp.jsx
  fundingboost/src/components/molecules/signUp/signUp.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/main/main.jsx
  fundingboost/src/components/organisms/contents/main/main.scss
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.jsx
  fundingboost/src/components/organisms/contents/mypay/mypay.jsx
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/components/pages/signUp-page/signUp-page.jsx
  fundingboost/src/components/pages/signUp-page/signUp-page.scss
  fundingboost/src/router.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#36 ✨ [FF-60] 마이페이지 지난 펀딩 이력, 친구 펀딩 기록 컴포넌트 배치
  fundingboost/src/assets/detail-section-icon.svg
  fundingboost/src/components/atoms/MyPageFriendFundingItem/mypage-friend-funding-item.jsx
  fundingboost/src/components/atoms/MyPageFriendFundingItem/mypage-friend-funding-item.scss
  fundingboost/src/components/atoms/MyPageMyFundingHistory/mypage-myfunding-history.jsx
  fundingboost/src/components/atoms/MyPageMyFundingHistory/mypage-myfunding-history.scss
  fundingboost/src/components/molecules/MyPageFriendFundingList/mypage-friend-funding-list.jsx
  fundingboost/src/components/molecules/MyPageFriendFundingList/mypage-friend-funding-list.scss
  fundingboost/src/components/molecules/MyPageMyFundingHistoryList/mypage-myfunding-history-list.jsx
  fundingboost/src/components/molecules/MyPageMyFundingHistoryList/mypage-myfunding-history-list.scss
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.scss
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.jsx
  fundingboost/src/components/organisms/contents/order-pay/order-pay.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#37 ✨ [FF-59] 마이페이지 배송지관리page, 위시리스트page, My리뷰 page 생성
  fundingboost/src/components/molecules/Single-friendFunding/single-friendFunding.scss
  fundingboost/src/components/molecules/deliveryAddress/deliveryAddress.jsx
  fundingboost/src/components/molecules/deliveryAddress/deliveryAddress.scss
  fundingboost/src/components/molecules/deliveryList/deliveryList.jsx
  fundingboost/src/components/molecules/deliveryList/deliveryList.scss
  fundingboost/src/components/molecules/reviewList/reviewList.jsx
  fundingboost/src/components/molecules/reviewList/reviewList.scss
  fundingboost/src/components/molecules/singleReview/singleReview.jsx
  fundingboost/src/components/molecules/singleReview/singleReview.scss
  fundingboost/src/components/molecules/wishList-SingleItem/wishList-SingleItem.jsx
  fundingboost/src/components/molecules/wishList-SingleItem/wishList-SingleItme.scss
  fundingboost/src/components/molecules/wishList/wishList.jsx
  fundingboost/src/components/molecules/wishList/wishList.scss
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.jsx
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.scss
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.scss
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.jsx
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.scss
Labels: :sparkles: Feature

#38 ✨ [FF-62] 쇼핑 상세 페이지 리팩토링, 마이페이지 구매내역 생성, 헤더 bug 수정
  fundingboost/src/assets/hamburgerIcon.png
  fundingboost/src/components/atoms/OrderProductDetail/orderproductdetail.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.jsx
  fundingboost/src/components/atoms/button/fundingNowBtn/fundingNowBtn.jsx
  fundingboost/src/components/atoms/button/fundingNowBtn/fundingNowBtn.scss
  fundingboost/src/components/atoms/button/purchaseBtn/purchaseBtn.jsx
  fundingboost/src/components/atoms/button/purchaseBtn/purchaseBtn.scss
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.jsx
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistItem/fundingRegistItem.jsx
  fundingboost/src/components/molecules/orderHistory-singleOrder/orderHistory-singleOrder.jsx
  fundingboost/src/components/molecules/orderHistory-singleOrder/orderHistory-singleOrder.scss
  fundingboost/src/components/molecules/orderHistoryList/orderHistoryList.jsx
  fundingboost/src/components/molecules/orderHistoryList/orderHistoryList.scss
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.jsx
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.scss
  fundingboost/src/components/organisms/contents/order-pay/order-pay.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/organisms/header/header.scss
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature

#39 ✨ [FF-61] 로그인 로그아웃 토큰 처리 및 Recoil 상태관리 적용, API 요청 헤더 토큰 비교 적용, 쇼핑 아이템 API 연결
  fundingboost/src/App.jsx
  fundingboost/src/api/axiosInstance.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.jsx
  fundingboost/src/components/atoms/button/friendfundingPaymentBtn/friendfundingPaymentBtn.jsx
  fundingboost/src/components/atoms/button/signUpBtn/signUpBtn.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-myfunding-extension-button/mypage-myfunding-extension-button.jsx
  fundingboost/src/components/molecules/Modal/GifthubOptionCount/gifthuboptioncount.jsx
  fundingboost/src/components/molecules/Mypage-Myfunding/mypage-myfunding-dofunding.jsx
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.jsx
  fundingboost/src/components/molecules/mainFunding/mainFunding.jsx
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.jsx
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.jsx
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.jsx
  fundingboost/src/components/organisms/contents/mypay/mypay.jsx
  fundingboost/src/components/organisms/contents/order-pay/order-pay.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
  fundingboost/src/index.js
  fundingboost/src/state/auth.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :postbox: API, :sparkles: Feature

#40 🐛 [FF-47] fix bug
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.scss
  fundingboost/src/components/molecules/signUp/signUp.jsx
  fundingboost/src/components/molecules/signUp/signUp.scss
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.jsx
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/organisms/contents/shopping/shopping.jsx
  fundingboost/src/components/organisms/header/header.scss
Labels: :lady_beetle: bug, :sparkles: Feature

#41 [FF-47] V2 refactor
  fundingboost/src/components/atoms/MyPageFriendFundingItem/mypage-friend-funding-item.jsx
  fundingboost/src/components/atoms/MyPageMyFundingHistory/mypage-myfunding-history.jsx
  fundingboost/src/components/atoms/MyPageMyFundingHistory/mypage-myfunding-history.scss
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/buttons/Mypage-Myfunding-Button/mypage-exchange-button/mypage-exchange-button.jsx
  fundingboost/src/components/atoms/mypage-myfunding-fin-btn/mypage-myfunding-fin-btn.jsx
  fundingboost/src/components/molecules/GifthubResult/gifthubresult.jsx
  fundingboost/src/components/molecules/GifthubResult/gifthubresult.scss
  fundingboost/src/components/molecules/MyPageFriendFundingList/mypage-friend-funding-list.jsx
  fundingboost/src/components/molecules/MyPageFriendFundingList/mypage-friend-funding-list.scss
  fundingboost/src/components/molecules/MyPageMyFundingHistoryList/mypage-myfunding-history-list.jsx
  fundingboost/src/components/molecules/MyPageMyFundingHistoryList/mypage-myfunding-history-list.scss
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.jsx
  fundingboost/src/components/organisms/contents/login/login.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.jsx
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/header/header.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
  fundingboost/src/components/pages/main-page/main-page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :postbox: API, :sparkles: Feature

#42 ✨ [FF-63] 마이페이지, 펀딩등록페이지, 상품 상세 페이지 리팩토링
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/Shopping-Detail-Title/shopping-detail-title.jsx
  fundingboost/src/components/atoms/button/FundingRegistBtn/fundingRegistBtn.jsx
  fundingboost/src/components/atoms/button/wishBtn/wishBtn.jsx
  fundingboost/src/components/atoms/fundingRegistModal/fundingRegistModal.jsx
  fundingboost/src/components/atoms/fundingRegistModal/fundingRegistModal.scss
  fundingboost/src/components/molecules/FundingRegist/FundingRegistDetails/fundingRegistDetails.jsx
  fundingboost/src/components/molecules/MypageProfile/mypageprofile.jsx
  fundingboost/src/components/molecules/deliveryAddress/deliveryAddress.jsx
  fundingboost/src/components/molecules/deliveryList/deliveryList.jsx
  fundingboost/src/components/molecules/orderHistory-singleOrder/orderHistory-singleOrder.jsx
  fundingboost/src/components/molecules/orderHistoryList/orderHistoryList.jsx
  fundingboost/src/components/molecules/reviewList/reviewList.jsx
  fundingboost/src/components/molecules/singleReview/singleReview.jsx
  fundingboost/src/components/molecules/wishList-SingleItem/wishList-SingleItem.jsx
  fundingboost/src/components/molecules/wishList/wishList.jsx
  fundingboost/src/components/molecules/wishList/wishList.scss
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.jsx
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.jsx
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :postbox: API, :sparkles: Feature

#43 ✨ [FF-66] 비회원 접근제한 모달창
  fundingboost/src/assets/reviewTestImg.jpg
  fundingboost/src/assets/reviewTestItmeImg.webp
  fundingboost/src/components/atoms/MyPageFriendFundingItem/mypage-friend-funding-item.jsx
  fundingboost/src/components/atoms/nonMemberModal/nonMemberModal.jsx
  fundingboost/src/components/atoms/nonMemberModal/nonMemberModal.scss
  fundingboost/src/components/molecules/singleReview/singleReview.jsx
  fundingboost/src/components/molecules/wishList-SingleItem/wishList-SingleItme.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/mypage-delivery-manage/mypage-delivery-mange.jsx
  fundingboost/src/components/organisms/contents/mypage-friend-history/mypage-friend-history.jsx
  fundingboost/src/components/organisms/contents/mypage-myfunding/mypage-myfunding.jsx
  fundingboost/src/components/organisms/contents/mypage-myhistory/mypage-myhistory.jsx
  fundingboost/src/components/organisms/contents/mypage-order-history/mypage-order-history.jsx
  fundingboost/src/components/organisms/contents/mypage-review/mypage-review.jsx
  fundingboost/src/components/organisms/contents/mypage-wishlist/mypage-wishlist.jsx
  fundingboost/src/components/organisms/contents/mypay/mypay.jsx
  fundingboost/src/components/organisms/contents/order-pay/order-pay.jsx
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
  fundingboost/src/components/pages/friendFundingDetail-page/friendFundingDetail-page.jsx
  fundingboost/src/components/pages/friendFundingPay-page/friendFundingPay-page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :sparkles: Feature

#44 ✨[FF-68] 아이템 수량에 맞게 전송, 친구펀딩, 장바구니 상품 없는 경우 컴포넌트 개발
  fundingboost/src/components/atoms/Shopping-Detail-Menu/shopping-detail-menu.jsx
  fundingboost/src/components/atoms/button/ShoppingNowBtn/shoppingNowBtn.jsx
  fundingboost/src/components/atoms/button/fundingNowBtn/fundingNowBtn.jsx
  fundingboost/src/components/atoms/nonMemberModal/nonMemberModal.scss
  fundingboost/src/components/molecules/GifthubResult/gifthubresult.jsx
  fundingboost/src/components/molecules/SingleGifthubItem/singlegifthubitem.jsx
  fundingboost/src/components/organisms/contents/FriendNonFunding/FriendNonFunding.jsx
  fundingboost/src/components/organisms/contents/FriendNonFunding/friendNonFunding.scss
  fundingboost/src/components/organisms/contents/gifthub/gifthub.jsx
  fundingboost/src/components/organisms/contents/gifthubNonItem/gifthubNonItem.jsx
  fundingboost/src/components/organisms/contents/gifthubNonItem/gifthubNonItem.scss
  fundingboost/src/components/organisms/contents/shopping-detail/shopping-detail.scss
  fundingboost/src/components/pages/friendFunding-page/friendFunding-page.jsx
  fundingboost/src/components/pages/fundingRegist-page/fundingRegist-Page.jsx
Labels: :hammer: Refactor, :lady_beetle: bug, :sparkles: Feature
